all: task14_1 task14_2 test task14_3 task14_4 task14_5 task14_6\
task16_1 task16_2  task16_3   task16_4

clean:
	rm task14_1 task14_2 test task14_3 task14_4 task14_5 task14_6\
 task16_1 task16_2  task16_3   task16_4
	
task16_4:task16_4.cpp
	g++ -g -o task16_4 task16_4.cpp
task16_3:task16_3.cpp
	g++ -g -o task16_3 task16_3.cpp
task16_2:task16_2.cpp
	g++ -g -o task16_2 task16_2.cpp
task16_1:task16_1.cpp
	g++ -g -o task16_1 task16_1.cpp
task14_6:task14_6.cpp
	g++ -g -o task14_6 task14_6.cpp
task14_5:task14_5.cpp
	g++ -g -o task14_5 task14_5.cpp
task14_4:task14_4.cpp
	g++ -g -o task14_4 task14_4.cpp
task14_3:task14_3.cpp
	g++ -g -o task14_3 task14_3.cpp
test:test.cpp
	g++ -g -o test test.cpp
task14_2:task14_2.cpp
	g++ -g -o task14_2  task14_2.cpp
task14_1:task14_1.cpp
	g++ -g -o task14_1  task14_1.cpp

