all:task15_3 task10_5 task13_5 task9_3 task13_3 task12_1 test_rand task8_10 test_ints taskdir_1 task14_2 task8_13 task8_5 task13_2 task8_11 make task15_1 task14_1 taskdir_3 erreo_1 task10_1 task13_4 test_scanf1 task9_5 test_scanf task11_2 task13_6 task8_9 task13_7 taskdir_6 task8_7 test_string test_point task11_3 taskdir_5 task13_1 file_access task8_8 preteatment_1 task10_2 file_utime file_rename task11_1 task8_6 task10_4 task8_4 task14_3 erreo_2 taskdir_2 task9_4 task9_2 task15_2 task8_12 task12_2 

task15_3:
	gcc -o task15_3 task15_3.c
task10_5:
	gcc -o task10_5 task10_5.c
task13_5:
	gcc -o task13_5 task13_5.c
task9_3:
	gcc -o task9_3 task9_3.c
task13_3:
	gcc -o task13_3 task13_3.c
task12_1:
	gcc -o task12_1 task12_1.c
test_rand:
	gcc -o test_rand test_rand.c
task8_10:
	gcc -o task8_10 task8_10.c
test_ints:
	gcc -o test_ints test_ints.c
taskdir_1:
	gcc -o taskdir_1 taskdir_1.c
task14_2:
	gcc -o task14_2 task14_2.c
task8_13:
	gcc -o task8_13 task8_13.c
task8_5:
	gcc -o task8_5 task8_5.c
task13_2:
	gcc -o task13_2 task13_2.c
task8_11:
	gcc -o task8_11 task8_11.c
make:
	gcc -o make make.c
task15_1:
	gcc -o task15_1 task15_1.c
task14_1:
	gcc -o task14_1 task14_1.c
taskdir_3:
	gcc -o taskdir_3 taskdir_3.c
erreo_1:
	gcc -o erreo_1 erreo_1.c
task10_1:
	gcc -o task10_1 task10_1.c
task13_4:
	gcc -o task13_4 task13_4.c
test_scanf1:
	gcc -o test_scanf1 test_scanf1.c
task9_5:
	gcc -o task9_5 task9_5.c
test_scanf:
	gcc -o test_scanf test_scanf.c
task11_2:
	gcc -o task11_2 task11_2.c
task13_6:
	gcc -o task13_6 task13_6.c
task8_9:
	gcc -o task8_9 task8_9.c
task13_7:
	gcc -o task13_7 task13_7.c
taskdir_6:
	gcc -o taskdir_6 taskdir_6.c
task8_7:
	gcc -o task8_7 task8_7.c
test_string:
	gcc -o test_string test_string.c
test_point:
	gcc -o test_point test_point.c
task11_3:
	gcc -o task11_3 task11_3.c
taskdir_5:
	gcc -o taskdir_5 taskdir_5.c
task13_1:
	gcc -o task13_1 task13_1.c
file_access:
	gcc -o file_access file_access.c
task8_8:
	gcc -o task8_8 task8_8.c
preteatment_1:
	gcc -o preteatment_1 preteatment_1.c
task10_2:
	gcc -o task10_2 task10_2.c
file_utime:
	gcc -o file_utime file_utime.c
file_rename:
	gcc -o file_rename file_rename.c
task11_1:
	gcc -o task11_1 task11_1.c
task8_6:
	gcc -o task8_6 task8_6.c
task10_4:
	gcc -o task10_4 task10_4.c
task8_4:
	gcc -o task8_4 task8_4.c
task14_3:
	gcc -o task14_3 task14_3.c
erreo_2:
	gcc -o erreo_2 erreo_2.c
taskdir_2:
	gcc -o taskdir_2 taskdir_2.c
task9_4:
	gcc -o task9_4 task9_4.c
task9_2:
	gcc -o task9_2 task9_2.c
task15_2:
	gcc -o task15_2 task15_2.c
task8_12:
	gcc -o task8_12 task8_12.c
task12_2:
	gcc -o task12_2 task12_2.c
clean:
	rm -f task15_3 task10_5 task13_5 task9_3 task13_3 task12_1 test_rand task8_10 test_ints taskdir_1 task14_2 task8_13 task8_5 task13_2 task8_11 make task15_1 task14_1 taskdir_3 erreo_1 task10_1 task13_4 test_scanf1 task9_5 test_scanf task11_2 task13_6 task8_9 task13_7 taskdir_6 task8_7 test_string test_point task11_3 taskdir_5 task13_1 file_access task8_8 preteatment_1 task10_2 file_utime file_rename task11_1 task8_6 task10_4 task8_4 task14_3 erreo_2 taskdir_2 task9_4 task9_2 task15_2 task8_12 task12_2 