all: task14_1 task14_2 test

clean:
	rm task14_1 task14_2 test
	

test:test.cpp
	g++ -g -o test test.cpp
task14_2:task14_2.cpp
	g++ -g -o task14_2  task14_2.cpp
task14_1:task14_1.cpp
	g++ -g -o task14_1  task14_1.cpp

